
services:

  postgres:
    image: postgres:13.0-alpine
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    
  pytest:
    build:
      dockerfile: tests/Dockerfile
    container_name: tests-pytest
    env_file:
      - .env
    depends_on:
      - postgres


  app:
    build:
      dockerfile: app/Dockerfile
    container_name: tron_service_app
    hostname: ${FASTAPI_HOST}
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      pytest:
        condition: service_completed_successfully

volumes:
  postgres_data:
